name: thai_idcard_reader_flutter_example
description: Demonstrates how to use the thai_idcard_reader_flutter plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  thai_idcard_reader_flutter:
    path: ../
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
