name: thai_idcard_reader_flutter
description: A plugin for communicating with ACS ACR39U Smart Card reader to read Thai ID card instantly.
version: 0.0.3
homepage: https://github.com/11dj/thai_idcard_reader_flutter
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.thai_idcard_reader_flutter
        pluginClass: ThaiIdcardReaderFlutterPlugin
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
